version: '3.3'
services:
  server:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    depends_on:
      - server
    env_file:
      - ./client/.env.development